# Supabase Edge Functions Configuration

# Environment variables for the functions
[global.env_vars]
# SMTP Configuration
SMTP_USERNAME = "fjfdobli@addu.edu.ph"
SMTP_PASSWORD = "Ferdinandj0hnD!1"
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
EMAIL_FROM = "noreply@opzons-printing.com"
EMAIL_FROM_NAME = "Opzon's Printing Press"

# Twilio Configuration
TWILIO_ACCOUNT_SID = "AC09fb91b896332341a45dda8dda0d37b7"
TWILIO_AUTH_TOKEN = "540ce601069a1fb7bc2a38b5db7f14f" 
TWILIO_PHONE_NUMBER = "+63932191736"

# Function-specific configurations
[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true